### ISSUE TITLE
Virtual Keyboard - Right arrow key mapped to Left arrow key.

### ISSUE THREAD

**Issue by solarmon** [retro-games-ltd/redquark-amiberry-rb#1]
**Describe the bug**

On the Virtual Keyboard, the Right arrow key mapped to Left arrow key.

**To Reproduce**

1. Load Amiga Test Kit
2. Go to the keyboard test
3. Bring up the Virtual Keyboard
4. select the right arrow key, but the left arrow key is selected. 

**Expected behavior**

I expect the right arrow key is activated when selecting the right arrow key on the virtual keyboard.

**Screenshots**
In the source code at https://github.com/retro-games-ltd/redquark-amiberry-rb/blob/redquark-v3_3/src/osdep/virtual_keyboard.cpp

You can clearly see the bug:

![image](https://user-images.githubusercontent.com/46369787/166695826-1215aa85-f3da-41a9-b38c-71558c5f4379.png)

**Comment by zxchris** [comment]
Fixed in 1.1.1
